# Generated by Django 5.2.7 on 2025-11-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskinfo',
            old_name='content',
            new_name='title',
        ),
        migrations.AddField(
            model_name='taskinfo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='taskinfo',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
